version: "3"
services:
  nats_service:
    container_name: nats
    entrypoint: '/nats-server -c nats-server.conf -DV'
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
  api_gateway:
    depends_on:
      - graphs_service
      - folders_service
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api_gateway
    ports:
      - 3000:3000
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  graphs_service:
    depends_on:
      - postgres
      - nats_service
    build:
      dockerfile: Dockerfile.dev
      context: ./graphs
    environment:
      - GRAPHS_SERVICE_HOST=0.0.0.0
      - GRAPHS_SERVICE_PORT=4000
      - GRAPHS_SERVICE_WEB_PORT=4001
      - FOLDERS_SERVICE_HOST=folders_service
      - FOLDERS_SERVICE_PORT=5000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=graphs-folders-microservice/graphs
    volumes:
      - /app/node_modules
      - ./graphs:/app
  folders_service:
    depends_on:
      - postgres
      - nats_service
    build:
      dockerfile: Dockerfile.dev
      context: ./folders
    environment:
      - FOLDERS_SERVICE_HOST=0.0.0.0
      - FOLDERS_SERVICE_PORT=5000
      - FOLDERS_SERVICE_WEB_PORT=5001
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=graphs-folders-microservice/folders
    volumes:
      - /app/node_modules
      - ./folders:/app
