apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service-main
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    -
      http:
        paths:
          -
            path: /graphs
            backend:
              serviceName: graphs-cluster-ip-service
              servicePort: 4001
          -
            path: /folders
            backend:
              serviceName: folders-cluster-ip-service
              servicePort: 5001
          -
            path: /search
            backend:
              serviceName: my-elasticsearch-client
              servicePort: 9200
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service-search-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    -
      http:
        paths:
          -
            path: /search(/|$)(.*)
            backend:
              serviceName: my-elasticsearch-client
              servicePort: 9200
