apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    -
      http:
        paths:
          -
            path: /graphs
            backend:
              serviceName: graphs-cluster-ip-service
              servicePort: 4001
          -
            path: /folders
            backend:
              serviceName: folders-cluster-ip-service
              servicePort: 5001
          -
            path: /search
            backend:
              serviceName: my-elasticsearch-client
              servicePort: 9200
          -
            path: /
            backend:
              serviceName: my-kafka-cp-control-center
              servicePort: 9021
